export default {
  id: "15,15",
  floor: [
    "gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr",
    "gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr",
    "gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr",
    "gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr",
    "gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr",
    "gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr",
    "gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr",
    "gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr",
    "gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr",
    "gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr gr",
  ],
  walls: [
    "rk rk rk rk rk rk rk rk rk rk rk rk rk rk rk rk",
    "rk .. .. .. .. .. .. .. .. .. .. .. .. .. .. rk",
    "rk .. rk .. .. .. .. .. .. .. .. .. .. rk .. rk",
    "rk .. .. .. .. .. .. .. .. .. .. .. .. .. .. rk",
    ".. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..",
    ".. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..",
    "rk .. .. .. .. .. .. .. .. .. .. .. .. .. .. rk",
    "rk .. rk .. .. .. .. .. .. .. .. .. .. rk .. rk",
    "rk .. .. .. .. .. .. .. .. .. .. .. .. .. .. rk",
    "rk rk rk rk rk rk rk .. .. rk rk rk rk rk rk rk",
  ],
  assets: [],
  enemies: [],
  chests: [],
};
