export default {
  id: "10,7",
  name: "Amber Wastes · Glassspring Oasis",
  floor: [
    "dt dt dt dt sa sa dt dt dt dt sa sa dt dt dt dt",
    "dt sa dt dt dt dt dt dt dt dt dt dt dt dt sa dt",
    "dt dt dt sa dt dt dt dt dt dt dt dt sa dt dt dt",
    "dt dt dt dt dt dt sw sw sw sw dt dt dt dt dt dt",
    "dt dt dt dt dt sw sw sw sw sw sw dt dt dt dt dt",
    "dt dt dt dt dt sw sw sw sw sw sw dt dt dt dt dt",
    "dt dt dt dt dt dt sw sw sw sw dt dt dt dt dt dt",
    "dt dt sa dt dt dt dt dt dt dt dt dt dt sa dt dt",
    "dt sa dt dt dt dt dt dt dt dt dt dt dt dt sa dt",
    "dt dt dt dt dt dt dt dt dt dt dt dt dt dt dt dt",
  ],
  walls: [
    "dc dc dc dc dc dc dc .. .. dc dc dc dc dc dc dc",
    "dc .. .. .. .. .. .. .. .. .. .. .. .. .. .. dc",
    "dc .. du du .. .. .. .. .. .. .. .. du du .. dc",
    "dc .. du du .. .. .. .. .. .. .. .. du du .. dc",
    ".. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..",
    ".. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..",
    "dc .. .. .. .. .. .. .. .. .. .. .. .. .. .. dc",
    "dc .. du du .. .. .. .. .. .. .. .. du du .. dc",
    "dc .. .. .. .. .. .. .. .. .. .. .. .. .. .. dc",
    "dc dc dc dc dc dc dc .. .. dc dc dc dc dc dc dc",
  ],
  assets: [
    { type: "desertOasis", x: 8, y: 5, solid: false },
    { type: "desertCactus", x: 3, y: 3, solid: false },
    { type: "desertCactus", x: 12, y: 7, solid: false },
    { type: "desertRock", x: 2, y: 7, solid: false },
    { type: "desertRock", x: 13, y: 3, solid: false },
    { type: "desertDryBush", x: 4, y: 8, solid: false },
    { type: "desertDryBush", x: 11, y: 2, solid: false },
    { type: "desertBones", x: 12, y: 2, solid: false },
  ],
};
