export default {
  id: "10,12",
  name: "Crystal Highlands · Prism Ascent",
  floor: [
    "cv cv cv cv cv cv cv xf xf cv cv cv cv cv cv cv",
    "cv cv cv cv cv cv xf xf xf xf cv cv cv cv cv cv",
    "cv cv cv xf xf xf xf xf xf xf xf xf cv cv cv cv",
    "cv cv cv xf cp cp cv xf xf cv cp cp xf cv cv cv",
    "cv cv cv xf cp cp cv xf xf cv cp cp xf cv cv cv",
    "cv cv cv xf xf xf cv xf xf cv xf xf xf cv cv cv",
    "cv cv cv cv cv xf xf xf xf xf xf cv cv cv cv cv",
    "cv cv cv cv cv cv xf xf xf xf cv cv cv cv cv cv",
    "cv cv cv cv cv cv cv xf xf cv cv cv cv cv cv cv",
    "cv cv cv cv cv cv cv xf xf cv cv cv cv cv cv cv",
  ],
  walls: [
    "cw cw cw cw cw cw cw .. .. cw cw cw cw cw cw cw",
    "cw .. .. .. .. .. .. .. .. .. .. .. .. .. .. cw",
    "cw .. xw xw .. .. .. .. .. .. .. .. xw xw .. cw",
    "cw .. xw xw .. .. .. .. .. .. .. .. xw xw .. cw",
    "cw .. .. .. .. .. .. .. .. .. .. .. .. .. .. cw",
    "cw .. .. .. .. .. .. .. .. .. .. .. .. .. .. cw",
    "cw .. xw .. .. .. .. .. .. .. .. .. .. xw .. cw",
    "cw .. xw .. .. .. .. .. .. .. .. .. .. xw .. cw",
    "cw .. .. .. .. .. .. .. .. .. .. .. .. .. .. cw",
    "cw cw cw cw cw cw cw .. .. cw cw cw cw cw cw cw",
  ],
  assets: [
    { type: "crystalLarge", x: 5, y: 3, solid: false },
    { type: "crystalLarge", x: 10, y: 6, solid: false },
    { type: "crystalSmall", x: 6, y: 6, solid: false },
    { type: "crystalSmall", x: 9, y: 3, solid: false },
    { type: "caveStalagmite", x: 3, y: 6, solid: false },
    { type: "caveStalagmite", x: 12, y: 3, solid: false },
    { type: "caveTorch", x: 6, y: 2, solid: false },
    { type: "caveTorch", x: 9, y: 7, solid: false },
  ],
};
