export default {
  id: "2,1",
  name: "Eastwind Meadow",
  floor: [
    "gggggggggggggggg",
    "gggggggggggggggg",
    "gggggggggggggggg",
    "gggggggggggggggg",
    "ppppppppgggggggg",
    "pppppppppppppggg",
    "gggggggppggggggg",
    "gggggggppggggggg",
    "gggggggppggggggg",
    "gggggggppggggggg",
  ],
  walls: [
    "TTTTTTTTTTTTTTTT",
    "T..............T",
    "T..............T",
    "T..............T",
    "...............T",
    "...............T",
    "T..............T",
    "T..............T",
    "T..............T",
    "TTTTTTT..TTTTTTT",
  ],
  assets: [
    { type: "forestTree", x: 3, y: 2 },
    { type: "forestTree", x: 13, y: 2 },
    { type: "forestBush", x: 4, y: 7 },
    { type: "forestStump", x: 12, y: 7 },
    { type: "forestTallGrass", x: 6, y: 3, solid: false },
    { type: "forestTallGrass", x: 10, y: 7, solid: false },
    { type: "forestFlowers", x: 9, y: 2, solid: false },
  ],
};
