export default {
  id: "1,2",
  name: "Applewood Orchard",
  floor: [
    "gggggggppggggggg",
    "gggggggppggggggg",
    "gggggggppggggggg",
    "gggggggppggggggg",
    "gggggggppppppppp",
    "gggggggppppppppp",
    "gggggggggggggggg",
    "gggggggggggggggg",
    "gggggggggggggggg",
    "gggggggggggggggg",
  ],
  walls: [
    "TTTTTTT..TTTTTTT",
    "T..............T",
    "T..............T",
    "T..............T",
    "T...............",
    "T...............",
    "T..............T",
    "T..............T",
    "T..............T",
    "TTTTTTTTTTTTTTTT",
  ],
  assets: [
    { type: "forestTree", x: 3, y: 3 },
    { type: "forestTree", x: 12, y: 3 },
    { type: "forestTree", x: 3, y: 7 },
    { type: "forestTree", x: 12, y: 7 },
    { type: "forestBush", x: 5, y: 6 },
    { type: "forestBush", x: 10, y: 6 },
    { type: "forestFlowers", x: 6, y: 2, solid: false },
    { type: "forestMushrooms", x: 9, y: 7, solid: false },
  ],
};
