export default {
  id: "1,2",
  name: "Applewood Orchard",
  floor: [
    "gggggggppggggggg",
    "gggggggppggggggg",
    "gggggggppggggggg",
    "gggggggppggggggg",
    "gggggggppppppppp",
    "gggggggppppppppp",
    "gggggggggggggggg",
    "gggggggggggggggg",
    "gggggggggggggggg",
    "gggggggggggggggg",
  ],
  walls: [
    "TTTTTTT..TTTTTTT",
    "T..............T",
    "T..............T",
    "T..............T",
    "T...............",
    "T...............",
    "T..............T",
    "T..............T",
    "T..............T",
    "TTTTTTTTTTTTTTTT",
  ],
  assets: [
    { type: "forestTree", x: 3, y: 3 },
    { type: "forestTree", x: 12, y: 3 },
    { type: "forestTree", x: 3, y: 7 },
    { type: "forestTree", x: 12, y: 7 },
    { type: "forestCanopyForeground", x: 3, y: 9, solid: false },
    { type: "forestCanopyForeground", x: 12, y: 9, solid: false },
    { type: "forestCanopyForeground", x: 3, y: 13, solid: false },
    { type: "forestCanopyForeground", x: 12, y: 13, solid: false },
    { type: "forestBush", x: 5, y: 6 },
    { type: "forestBush", x: 10, y: 6 },
    { type: "forestBush", x: 5, y: 2, solid: false },
    { type: "forestBush", x: 10, y: 2, solid: false },
    { type: "forestFlowers", x: 6, y: 2, solid: false },
    { type: "forestFlowers", x: 11, y: 5, solid: false },
    { type: "forestMushrooms", x: 9, y: 7, solid: false },
    { type: "forestMushrooms", x: 2, y: 5, solid: false },
    { type: "forestStump", x: 14, y: 5, solid: false },
    { type: "forestLog", x: 5, y: 8, solid: false },
    { type: "forestTallGrass", x: 13, y: 5, solid: false },
    { type: "forestCliffLipForeground", x: 6, y: 8, solid: false },
    { type: "merchantTraveler", x: 10, y: 5, solid: false },
  ],
};
