export default {
  id: "4,12",
  name: "Sunscar Desert · Caravan Scar",
  floor: [
    "dt dt dt sa dt dt dt dt dt dt dt dt sa dt dt dt",
    "dt dt sa dt dt dt dt dt dt dt dt dt dt sa dt dt",
    "dt dt dt dt dt sa dt dt dt dt sa dt dt dt dt dt",
    "dt dt dt dt dt dt dt dt dt dt dt dt dt dt dt dt",
    "dt dt dt dt dt dt dt dt dt dt dt dt dt dt dt dt",
    "dt dt dt dt dt dt dt dt dt dt dt dt dt dt dt dt",
    "dt dt dt dt sa dt dt dt dt dt dt sa dt dt dt dt",
    "dt dt dt sa dt dt dt dt dt dt dt dt sa dt dt dt",
    "dt dt dt dt dt dt dt dt dt dt dt dt dt dt dt dt",
    "dt dt dt dt dt dt dt dt dt dt dt dt dt dt dt dt",
  ],
  walls: [
    "dc dc dc dc dc dc dc .. .. dc dc dc dc dc dc dc",
    "dc .. .. .. .. .. .. .. .. .. .. .. .. .. .. dc",
    "dc .. du du .. .. .. .. .. .. .. .. du du .. dc",
    "dc .. du du .. .. .. .. .. .. .. .. du du .. dc",
    ".. .. .. .. .. .. .. .. .. .. .. .. .. .. .. dc",
    ".. .. .. .. .. .. .. .. .. .. .. .. .. .. .. dc",
    "dc .. .. .. du du .. .. .. .. du du .. .. .. dc",
    "dc .. .. .. du du .. .. .. .. du du .. .. .. dc",
    "dc .. .. .. .. .. .. .. .. .. .. .. .. .. .. dc",
    "dc dc dc dc dc dc dc .. .. dc dc dc dc dc dc dc",
  ],
  assets: [
    { type: "desertCactus", x: 3, y: 3, solid: false },
    { type: "desertCactus", x: 12, y: 6, solid: false },
    { type: "desertCactus", x: 13, y: 2, solid: false },
    { type: "desertRock", x: 4, y: 7, solid: false },
    { type: "desertRock", x: 11, y: 3, solid: false },
    { type: "desertDryBush", x: 2, y: 7, solid: false },
    { type: "desertDryBush", x: 13, y: 7, solid: false },
    { type: "desertBones", x: 8, y: 3, solid: false },
    { type: "desertRuins", x: 10, y: 7, solid: false },
  ],
};
