export default {
  id: "2,2",
  name: "Millpond Crossing",
  floor: [
    "gggggggppggggggg",
    "gggggggppggggggg",
    "ggggwwwbbwwwgggg",
    "ggggwwwbbwwwgggg",
    "ppppwwwbbwwwpppp",
    "ppppwwwbbwwwpppp",
    "ggggwwwbbwwwgggg",
    "ggggwwwbbwwwgggg",
    "gggggggggggggggg",
    "gggggggggggggggg",
  ],
  walls: [
    "TTTTTTT..TTTTTTT",
    "T..............T",
    "T..............T",
    "T..............T",
    "................",
    "................",
    "T..............T",
    "T..............T",
    "T..............T",
    "TTTTTTTTTTTTTTTT",
  ],
  assets: [
    { type: "forestTree", x: 2, y: 2 },
    { type: "forestTree", x: 13, y: 2 },
    { type: "forestCanopyForeground", x: 2, y: 8, solid: false },
    { type: "forestCanopyForeground", x: 13, y: 8, solid: false },
    { type: "coastReeds", x: 4, y: 3, solid: false },
    { type: "coastReeds", x: 11, y: 6, solid: false },
    { type: "coastReeds", x: 4, y: 6, solid: false },
    { type: "coastReeds", x: 11, y: 3, solid: false },
    { type: "coastLilyPad", x: 5, y: 6, solid: false },
    { type: "coastLilyPad", x: 10, y: 3, solid: false },
    { type: "coastFoam", x: 5, y: 3, solid: false },
    { type: "coastFoam", x: 10, y: 6, solid: false },
    { type: "forestBridgeApproach", x: 7, y: 2, solid: false },
    { type: "forestBridgeApproach", x: 8, y: 7, solid: false },
    { type: "forestPathStones", x: 6, y: 4, solid: false },
    { type: "forestPathStones", x: 9, y: 5, solid: false },
    { type: "forestFireflyOverlay", x: 5, y: 7, solid: false },
    { type: "forestFireflyOverlay", x: 10, y: 7, solid: false },
    { type: "villageSign", x: 13, y: 6, solid: false },
    { type: "villageLamp", x: 3, y: 5, solid: false },
    { type: "villageLamp", x: 12, y: 5, solid: false },
    { type: "forestFlowers", x: 2, y: 7, solid: false },
    { type: "forestMushrooms", x: 13, y: 7, solid: false },
    { type: "forestCliffLipForeground", x: 6, y: 8, solid: false },
    { type: "forestCliffLipForeground", x: 9, y: 8, solid: false },
  ],
};
