export default {
  id: "1,1",
  name: "Willowbrook Village",
  floor: [
    "gggggggppggggggg",
    "gggggggppggggggg",
    "gggggggppggggggg",
    "gggggggppggggggg",
    "pppppppppppppppp",
    "pppppppppppppppp",
    "gggggggppggggggg",
    "gggggggppggggggg",
    "gggggggppggggggg",
    "gggggggppggggggg",
  ],
  walls: [
    "TTTTTTT..TTTTTTT",
    "T..............T",
    "T..............T",
    "T..............T",
    "................",
    "................",
    "T..............T",
    "T..............T",
    "T..............T",
    "TTTTTTT..TTTTTTT",
  ],
  assets: [
    {
      type: "villageShop", x: 4, y: 3,
      collision: { left: 2, right: 2, top: 1, bottom: 0 },
    },
    {
      type: "villageHouse", x: 3, y: 7,
      collision: { left: 2, right: 2, top: 1, bottom: 0 },
    },
    {
      type: "villageHouse", x: 13, y: 7,
      collision: { left: 2, right: 2, top: 1, bottom: 0 },
    },
    { type: "villageWell", x: 11, y: 5 },
    { type: "villageSign", x: 6, y: 5, solid: false },
    { type: "villageLamp", x: 3, y: 4 },
    { type: "villageLamp", x: 13, y: 4 },
    { type: "forestFlowers", x: 2, y: 2, solid: false },
    { type: "forestFlowers", x: 13, y: 2, solid: false },
    { type: "villagerGardener", x: 6, y: 8 },
    { type: "villagerMechanic", x: 10, y: 8 },
  ],
};
