export default {
  id: "1,0",
  name: "Hero's Grove",
  floor: [
    "gggggggggggggggg",
    "gggggggggggggggg",
    "gggggggggggggggg",
    "gggggggggggggggg",
    "gggggggppppppppp",
    "gggggggppppppppp",
    "gggggggppggggggg",
    "gggggggppggggggg",
    "gggggggppggggggg",
    "gggggggppggggggg",
  ],
  walls: [
    "TTTTTTTTTTTTTTTT",
    "T..............T",
    "T..............T",
    "T..............T",
    "T...............",
    "T...............",
    "T..............T",
    "T..............T",
    "T..............T",
    "TTTTTTT..TTTTTTT",
  ],
  assets: [
    { type: "forestTree", x: 3, y: 3 },
    { type: "forestTree", x: 13, y: 2 },
    { type: "forestBush", x: 4, y: 6 },
    { type: "forestBush", x: 12, y: 7 },
    { type: "forestMushrooms", x: 6, y: 2, solid: false },
    { type: "forestFlowers", x: 10, y: 6, solid: false },
    { type: "villageSign", x: 9, y: 7, solid: false },
  ],
};
