export default {
  id: "3,12",
  name: "Sunscar Desert · Broken Colonnade",
  floor: [
    "dt dt sa dt dt dt dt dt dt dt dt sa dt dt dt dt",
    "dt sa sa dt dt dt dt dt dt dt dt dt dt dt dt dt",
    "dt dt dt dt dt dt sa dt dt dt dt dt sa dt dt dt",
    "dt dt dt sa dt dt dt dt dt dt dt dt dt dt dt dt",
    "dt dt dt dt dt dt dt dt dt dt dt dt dt dt dt dt",
    "dt dt dt dt dt dt dt dt dt dt dt dt dt dt dt dt",
    "dt dt dt dt dt sa dt dt dt dt dt dt dt dt sa dt",
    "dt dt sa dt dt dt dt dt dt sa dt dt dt dt dt dt",
    "dt dt dt dt dt dt dt dt dt dt dt dt dt dt dt dt",
    "dt dt dt dt dt dt dt dt dt dt dt dt dt dt dt dt",
  ],
  walls: [
    "dc dc dc dc dc dc dc .. .. dc dc dc dc dc dc dc",
    "dc .. .. .. .. .. .. .. .. .. .. .. .. .. .. dc",
    "dc .. du du du .. .. .. .. .. .. du du du .. dc",
    "dc .. du du du .. .. .. .. .. .. du du du .. dc",
    "dc .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..",
    "dc .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..",
    "dc .. .. du du .. .. .. .. .. .. du du .. .. dc",
    "dc .. .. du du .. .. .. .. .. .. du du .. .. dc",
    "dc .. .. .. .. .. .. .. .. .. .. .. .. .. .. dc",
    "dc dc dc dc dc dc dc dc dc dc dc dc dc dc dc dc",
  ],
  assets: [
    { type: "desertRuins", x: 5, y: 4, solid: false },
    { type: "desertRuins", x: 11, y: 6, solid: false },
    { type: "desertCactus", x: 2, y: 6, solid: false },
    { type: "desertCactus", x: 13, y: 3, solid: false },
    { type: "desertRock", x: 3, y: 8, solid: false },
    { type: "desertRock", x: 13, y: 8, solid: false },
    { type: "desertBones", x: 9, y: 3, solid: false },
    { type: "desertDryBush", x: 10, y: 8, solid: false },
  ],
};
