export default {
  id: "12,2",
  name: "Stormbreak Coast · Gullhook Cove",
  floor: [
    "ow ow ow ow ow ow ow ow ow ow ow ow ow ow ow ow",
    "ow ow ow ow ow ow ow sw sw sw ow ow ow ow ow ow",
    "ow ow ow ow ow sw sw sw sw sw sw ow ow ow ow ow",
    "sh sh sh sh sh sh sw sw sw sw ow ow ow ow ow ow",
    "sh sh sh sh sh sh sh sw sw ow ow ow ow ow ow ow",
    "sh sh sh sh sh sh sh sw sw ow ow ow ow ow ow ow",
    "sh sh sh sh sh sh sw sw sw sw ow ow ow ow ow ow",
    "ow ow ow ow ow sw sw sw sw sw sw ow ow ow ow ow",
    "ow ow ow ow ow ow ow sw sw sw ow ow ow ow ow ow",
    "ow ow ow ow ow ow ow ow ow ow ow ow ow ow ow ow",
  ],
  assets: [
    { type: "coastDock", x: 6, y: 5, solid: false },
    { type: "coastBoat", x: 9, y: 5, solid: false },
    { type: "coastFoam", x: 7, y: 3, solid: false },
    { type: "coastFoam", x: 7, y: 7, solid: false },
    { type: "coastReeds", x: 4, y: 3, solid: false },
    { type: "coastReeds", x: 5, y: 7, solid: false },
    { type: "coastLilyPad", x: 8, y: 7, solid: false },
  ],
};
