export default {
  id: "1,1",
  name: "Willowbrook Village",
  floor: [
    "gggggggppggggggg",
    "gggggggppggggggg",
    "gggggggppggggggg",
    "gggggggppggggggg",
    "pppppppppppppppp",
    "pppppppppppppppp",
    "gggggggppggggggg",
    "gggggggppggggggg",
    "gggggggppggggggg",
    "gggggggppggggggg",
  ],
  walls: [
    "tr bu rk tr lg bu tr .. .. rk bu lg tr rk bu tr",
    "bu .. .. .. .. .. .. .. .. .. .. .. .. .. .. rk",
    "rk .. .. .. .. .. .. .. .. .. .. .. .. .. .. tr",
    "tr .. .. .. .. .. .. .. .. .. .. .. .. .. .. bu",
    ".. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..",
    ".. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..",
    "bu .. .. .. .. .. .. .. .. .. .. .. .. .. .. tr",
    "rk .. .. .. .. .. .. .. .. .. .. .. .. .. .. bu",
    "tr .. .. .. .. .. .. .. .. .. .. .. .. .. .. rk",
    "bu tr lg rk bu tr rk .. .. tr bu rk lg tr bu rk",
  ],
  assets: [
    {
      type: "villageShop", x: 4, y: 3,
      collision: { left: 2, right: 2, top: 1, bottom: 0 },
    },
    {
      type: "villageHouse", x: 3, y: 7,
      collision: { left: 2, right: 2, top: 1, bottom: 0 },
    },
    {
      type: "villageHouse", x: 13, y: 7,
      collision: { left: 2, right: 2, top: 1, bottom: 0 },
    },
    { type: "villageWell", x: 11, y: 5 },
    { type: "villageSign", x: 6, y: 5, solid: false },
    { type: "villageLamp", x: 3, y: 4 },
    { type: "villageLamp", x: 13, y: 4 },
    { type: "villageLamp", x: 6, y: 7, solid: false },
    { type: "villageLamp", x: 9, y: 2, solid: false },
    { type: "villageFence", x: 1, y: 3, solid: false },
    { type: "villageFence", x: 14, y: 3, solid: false },
    { type: "villageFence", x: 2, y: 1, solid: false },
    { type: "villageFence", x: 13, y: 1, solid: false },
    { type: "forestFlowers", x: 2, y: 2, solid: false },
    { type: "forestFlowers", x: 13, y: 2, solid: false },
    { type: "forestFlowers", x: 5, y: 8, solid: false },
    { type: "forestMushrooms", x: 11, y: 8, solid: false },
    { type: "forestPathStones", x: 7, y: 3, solid: false },
    { type: "forestPathStones", x: 8, y: 6, solid: false },
    { type: "forestFireflyOverlay", x: 5, y: 6, solid: false },
    { type: "forestFireflyOverlay", x: 11, y: 6, solid: false },
    { type: "forestTree", x: 1, y: 2 },
    { type: "forestTree", x: 14, y: 2 },
    { type: "forestTree", x: 4, y: 1, solid: false },
    { type: "forestTree", x: 11, y: 1, solid: false },
    { type: "forestCanopyForeground", x: 1, y: 8, solid: false },
    { type: "forestCanopyForeground", x: 14, y: 8, solid: false },
    { type: "forestCanopyForeground", x: 4, y: 9, solid: false },
    { type: "forestCanopyForeground", x: 11, y: 9, solid: false },
    { type: "forestCliffLipForeground", x: 5, y: 8, solid: false },
    { type: "forestCliffLipForeground", x: 10, y: 8, solid: false },
    { type: "villagerGardener", x: 6, y: 8 },
    { type: "villagerMechanic", x: 10, y: 8 },
  ],
};
