export default {
  id: "12,6",
  name: "Stormbreak Coast · Breaker Pier",
  floor: [
    "ow ow ow ow ow ow ow ow ow ow ow ow ow ow ow ow",
    "ow ow ow ow ow ow sw sw sw sw ow ow ow ow ow ow",
    "ow ow ow ow sw sw sw sw sw sw sw sw ow ow ow ow",
    "sh sh sh sh sh sh sw sw sw sw sw ow ow ow ow ow",
    "sh sh sh sh sh sh sh sh sw sw ow ow ow ow ow ow",
    "sh sh sh sh sh sh sh sh sw sw ow ow ow ow ow ow",
    "sh sh sh sh sh sh sw sw sw sw sw ow ow ow ow ow",
    "ow ow ow ow sw sw sw sw sw sw sw sw ow ow ow ow",
    "ow ow ow ow ow ow sw sw sw sw ow ow ow ow ow ow",
    "ow ow ow ow ow ow ow ow ow ow ow ow ow ow ow ow",
  ],
  assets: [
    { type: "coastDock", x: 7, y: 5, solid: false },
    { type: "coastDock", x: 8, y: 5, solid: false },
    { type: "coastBoat", x: 10, y: 6, solid: false },
    { type: "coastFoam", x: 6, y: 3, solid: false },
    { type: "coastFoam", x: 7, y: 7, solid: false },
    { type: "coastReeds", x: 4, y: 7, solid: false },
    { type: "coastCoral", x: 11, y: 3, solid: false },
  ],
};
