export default {
  id: "8,13",
  name: "Crystal Highlands · Echo Gallery",
  floor: [
    "cv cv cv cv cv cv cv cv cv cv cv cv cv cv cv cv",
    "cv cv cv xf xf cv cv cv cv cv cv xf xf cv cv cv",
    "cv cv cv xf xf cv cp cp cp cp cv xf xf cv cv cv",
    "cv cv cv xf xf cv cp cp cp cp cv xf xf cv cv cv",
    "cv cv cv cv cv cv cv cv cv cv cv cv cv cv cv cv",
    "cv cv cv cv cv cv cv cv cv cv cv cv cv cv cv cv",
    "cv cv cv xf xf cv cp cp cp cp cv xf xf cv cv cv",
    "cv cv cv xf xf cv cp cp cp cp cv xf xf cv cv cv",
    "cv cv cv xf xf cv cv cv cv cv cv xf xf cv cv cv",
    "cv cv cv cv cv cv cv cv cv cv cv cv cv cv cv cv",
  ],
  walls: [
    "cw cw cw cw cw cw cw cw cw cw cw cw cw cw cw cw",
    "cw .. .. .. .. .. .. .. .. .. .. .. .. .. .. cw",
    "cw .. xw xw .. .. .. .. .. .. .. xw xw .. .. cw",
    "cw .. xw xw .. .. .. .. .. .. .. xw xw .. .. cw",
    ".. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..",
    ".. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..",
    "cw .. xw .. .. .. .. .. .. .. .. .. xw .. .. cw",
    "cw .. xw .. .. .. .. .. .. .. .. .. xw .. .. cw",
    "cw .. .. .. .. .. .. .. .. .. .. .. .. .. .. cw",
    "cw cw cw cw cw cw cw cw cw cw cw cw cw cw cw cw",
  ],
  assets: [
    { type: "crystalLarge", x: 3, y: 3, solid: false },
    { type: "crystalLarge", x: 12, y: 6, solid: false },
    { type: "crystalSmall", x: 4, y: 7, solid: false },
    { type: "crystalSmall", x: 11, y: 2, solid: false },
    { type: "caveBones", x: 5, y: 7, solid: false },
    { type: "caveStalagmite", x: 13, y: 7, solid: false },
    { type: "caveTorch", x: 6, y: 3, solid: false },
    { type: "caveTorch", x: 9, y: 6, solid: false },
  ],
};
