export default {
  id: "d01:0,2", name: "Root Cellar", variant: 0,
  wallRects: [[2, 2, 4, 2], [10, 2, 4, 2], [3, 6, 3, 2], [10, 6, 3, 2]],
  floor: [
    ".. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..",
    ".. mf mf mf mf mf mf mf mf mf mf mf mf mf mf ..",
    ".. mf mw mw mw mw mf mf mf mf mw mw mw mw mf ..",
    ".. mf mw mw mw mw mf mf mf mf mw mw mw mw mf ..",
    ".. mf mf mf mf mf mf mf mf mf mf mf mf mf mf ..",
    ".. mf mf mf mf mf xf xf xf xf mf mf mf mf mf ..",
    ".. mf mf mw mw mw xf xf xf xf mw mw mw mf mf ..",
    ".. mf mf mw mw mw mf mf mf mf mw mw mw mf mf ..",
    ".. mf mf mf mf mf mf mf mf mf mf mf mf mf mf ..",
    ".. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..",
  ],
  assets: [
    { type: "dungeonPot", x: 3, y: 5 },
    { type: "dungeonCrate", x: 12, y: 5 },
    { type: "caveBones", x: 8, y: 6, solid: false },
    { type: "rootboundRootGrowth", x: 4, y: 4, solid: false },
    { type: "rootboundRootGrowth", x: 11, y: 7, solid: false },
    { type: "rootboundFloorCracks", x: 7, y: 5, solid: false },
    { type: "rootboundHangingRootsForeground", x: 4, y: 8, solid: false },
    { type: "rootboundHangingRootsForeground", x: 11, y: 8, solid: false },
  ],
};
