export default {
  id: "d01:1,1", name: "Four-Root Hall", variant: 0,
  wallRects: [[2, 2, 4, 1], [10, 2, 4, 1], [2, 7, 3, 1], [11, 7, 3, 1]],
  floor: [
    ".. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..",
    ".. mf mf mf mf mf mf mf mf mf mf mf mf mf mf ..",
    ".. mf mw mw mw mw mf mf mf mf mw mw mw mw mf ..",
    ".. mf mf mf mf mf xf xf xf xf mf mf mf mf mf ..",
    ".. mf mf mf mf xf xf ps ps xf xf mf mf mf mf ..",
    ".. mf mf mf mf xf xf ps ps xf xf mf mf mf mf ..",
    ".. mf mf mf mf mf xf xf xf xf mf mf mf mf mf ..",
    ".. mf mw mw mw mf mf mf mf mf mf mw mw mw mf ..",
    ".. mf mf mf mf mf mf mf mf mf mf mf mf mf mf ..",
    ".. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..",
  ],
  assets: [
    { type: "dungeonStatue", x: 3, y: 4 },
    { type: "dungeonStatue", x: 12, y: 4, solid: false },
    { type: "dungeonTerminal", x: 12, y: 6, solid: false },
    { type: "dungeonBarrier", x: 7, y: 6, solid: false },
    { type: "dungeonPillar", x: 5, y: 3, solid: false },
    { type: "dungeonPillar", x: 10, y: 3, solid: false },
    { type: "dungeonPillar", x: 5, y: 6, solid: false },
    { type: "dungeonPillar", x: 10, y: 6, solid: false },
    { type: "crystalLarge", x: 7, y: 4, solid: false },
    { type: "crystalLarge", x: 8, y: 4, solid: false },
    { type: "crystalSmall", x: 6, y: 3, solid: false },
    { type: "crystalSmall", x: 9, y: 3, solid: false },
    { type: "crystalSmall", x: 6, y: 6, solid: false },
    { type: "crystalSmall", x: 9, y: 6, solid: false },
    { type: "caveTorch", x: 3, y: 3, solid: false },
    { type: "caveTorch", x: 12, y: 3, solid: false },
  ],
};
