export default {
  id: "d01:2,2", name: "Flooded Roots", variant: 0,
  wallRects: [[3, 2, 3, 2], [10, 2, 3, 2], [3, 6, 2, 2], [11, 5, 2, 3]],
  floor: [
    ".. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..",
    ".. mf mf mf mf mf mf mf mf mf mf mf mf mf mf ..",
    ".. mf mf mw mw mw mf sw sw sw mf mw mw mw mf ..",
    ".. mf mf mw mw mw sw sw sw sw sw mw mw mw mf ..",
    ".. mf mf mf mf mf sw sw sw sw sw mf mf mf mf ..",
    ".. mf mf mf mf mf sw sw sw sw sw mf mw mw mf ..",
    ".. mf mf mw mw mf sw sw sw sw sw mf mw mw mf ..",
    ".. mf mf mw mw mf mf sw sw sw mf mf mw mw mf ..",
    ".. mf mf mf mf mf mf mf mf mf mf mf mf mf mf ..",
    ".. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..",
  ],
  assets: [
    { type: "caveTorch", x: 7, y: 6, solid: false },
    { type: "caveStalagmite", x: 13, y: 3 },
    { type: "rootboundRootGrowth", x: 4, y: 6, solid: false },
    { type: "rootboundRootGrowth", x: 11, y: 5, solid: false },
    { type: "coastReeds", x: 6, y: 5, solid: false },
    { type: "coastReeds", x: 9, y: 5, solid: false },
    { type: "coastLilyPad", x: 7, y: 4, solid: false },
    { type: "rootboundFloorCracks", x: 3, y: 4, solid: false },
    { type: "rootboundHangingRootsForeground", x: 5, y: 8, solid: false },
    { type: "rootboundHangingRootsForeground", x: 10, y: 8, solid: false },
  ],
};
