export default {
  id: "d01:1,2", name: "Temple Threshold", variant: 0,
  wallRects: [[2, 2, 3, 5], [11, 2, 3, 5]],
  floor: [
    ".. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..",
    ".. mf mf mf mf mf mf mf mf mf mf mf mf mf mf ..",
    ".. mf mw mw mw mf mf mf mf mf mf mw mw mw mf ..",
    ".. mf mw mw mw mf mf ps mf mf mf mf mw mw mw mf ..",
    ".. mf mw mw mw mf mf mf tm mf mf mw mw mw mf ..",
    ".. mf mw mw mw mf mf mf mf mf mf mw mw mw mf ..",
    ".. mf mw mw mw mf mf ps mf mf mf mf mw mw mw mf ..",
    ".. mf mf mf mf mf mf mf mf mf mf mf mf mf mf ..",
    ".. mf mf mf mf mf mf mf mf mf mf mf mf mf mf ..",
    ".. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..",
  ],
  assets: [
    { type: "rootboundDoor", x: 7, y: 1, solid: false },
    { type: "dungeonPillar", x: 5, y: 7 },
    { type: "dungeonPillar", x: 10, y: 7 },
    { type: "dungeonStatue", x: 4, y: 5, solid: false },
    { type: "dungeonStatue", x: 11, y: 5, solid: false },
    { type: "dungeonTerminal", x: 8, y: 4, solid: false },
    { type: "caveTorch", x: 5, y: 2, solid: false },
    { type: "caveTorch", x: 10, y: 2, solid: false },
    { type: "crystalSmall", x: 6, y: 3, solid: false },
    { type: "crystalSmall", x: 9, y: 3, solid: false },
    { type: "crystalSmall", x: 6, y: 6, solid: false },
    { type: "crystalSmall", x: 9, y: 6, solid: false },
    { type: "dungeonPot", x: 3, y: 7, solid: false },
    { type: "dungeonPot", x: 12, y: 7, solid: false },
    { type: "rootboundArchForeground", x: 7, y: 7, solid: false },
    { type: "rootboundHangingRootsForeground", x: 3, y: 8, solid: false },
    { type: "rootboundHangingRootsForeground", x: 12, y: 8, solid: false },
  ],
};
