export default {
  id: "d01:0,1", name: "Keeper's Key", variant: 0,
  wallRects: [[3, 2, 2, 2], [11, 2, 2, 3], [3, 7, 4, 1], [10, 7, 3, 1]],
  floor: [
    ".. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..",
    ".. mf mf mf mf mf mf mf mf mf mf mf mf mf mf ..",
    ".. mf mf mw mw mf mf mf mf mf mf mw mw mf mf ..",
    ".. mf mf mw mw mf xf xf xf xf mf mw mw mf mf ..",
    ".. mf mf mf mf xf xf mf mf xf xf mf mf mf mf ..",
    ".. mf mf mf mf xf ps mf mf xf xf mf mf mf mf ..",
    ".. mf mf mf mf xf xf xf xf xf xf mf mf mf mf ..",
    ".. mf mf mw mw mw mw mf mf mf mf mw mw mw mf ..",
    ".. mf mf mf mf mf mf mf mf mf mf mf mf mf mf ..",
    ".. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..",
  ],
  assets: [
    { type: "dungeonStatue", x: 3, y: 5 },
    { type: "dungeonSwitch", x: 6, y: 5 },
    { type: "dungeonPillar", x: 12, y: 6 },
    { type: "dungeonPillar", x: 3, y: 2, solid: false },
    { type: "caveTorch", x: 6, y: 2, solid: false },
    { type: "caveTorch", x: 9, y: 2, solid: false },
    { type: "crystalLarge", x: 8, y: 4, solid: false },
    { type: "crystalSmall", x: 7, y: 4, solid: false },
    { type: "crystalSmall", x: 9, y: 5, solid: false },
    { type: "dungeonTerminal", x: 11, y: 3, solid: false },
    { type: "dungeonPot", x: 4, y: 7, solid: false },
    { type: "dungeonPot", x: 11, y: 7, solid: false },
    { type: "forestStump", x: 5, y: 7, solid: false },
    { type: "forestTallGrass", x: 4, y: 6, solid: false },
    { type: "forestTallGrass", x: 5, y: 6, solid: false },
    { type: "rootboundArchForeground", x: 8, y: 9, solid: false },
    { type: "rootboundHangingRootsForeground", x: 4, y: 8, solid: false },
    { type: "rootboundHangingRootsForeground", x: 11, y: 8, solid: false },
  ],
};
