export default {
  id: "d01:1,0", name: "Heartroot Sanctum", variant: 0,
  wallRects: [[2, 2, 3, 2], [11, 2, 3, 2], [2, 7, 4, 1], [10, 7, 4, 1]],
  floor: [
    ".. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..",
    ".. mf mf mf mf mf mf mf mf mf mf mf mf mf mf ..",
    ".. mf mw mw mw mf mf xf xf mf mf mw mw mw mf ..",
    ".. mf mw mw mw mf xf xf xf xf mf mw mw mw mf ..",
    ".. mf mf mf mf xf xf xf xf xf xf mf mf mf mf ..",
    ".. mf mf mf mf xf xf xf xf xf xf mf mf mf mf ..",
    ".. mf mf mf mf mf xf xf xf xf mf mf mf mf mf ..",
    ".. mf mw mw mw mw mf mf mf mf mw mw mw mw mf ..",
    ".. mf mf mf mf mf mf mf mf mf mf mf mf mf mf ..",
    ".. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..",
  ],
  assets: [
    { type: "dungeonStatue", x: 3, y: 5 },
    { type: "dungeonStatue", x: 12, y: 5 },
    { type: "dungeonPillar", x: 4, y: 3, solid: false },
    { type: "dungeonPillar", x: 11, y: 3, solid: false },
    { type: "caveTorch", x: 5, y: 2, solid: false },
    { type: "caveTorch", x: 10, y: 2, solid: false },
    { type: "caveTorch", x: 4, y: 6, solid: false },
    { type: "caveTorch", x: 11, y: 6, solid: false },
    { type: "crystalLarge", x: 7, y: 3, solid: false },
    { type: "crystalLarge", x: 8, y: 3, solid: false },
    { type: "crystalLarge", x: 7, y: 5, solid: false },
    { type: "crystalLarge", x: 8, y: 5, solid: false },
    { type: "crystalSmall", x: 6, y: 4, solid: false },
    { type: "crystalSmall", x: 9, y: 4, solid: false },
    { type: "dungeonTerminal", x: 8, y: 7, solid: false },
    { type: "dungeonPot", x: 3, y: 7, solid: false },
    { type: "dungeonPot", x: 12, y: 7, solid: false },
    { type: "dungeonBarrier", x: 7, y: 1, solid: false },
    { type: "rootboundArchForeground", x: 7, y: 9, solid: false },
    { type: "rootboundArchForeground", x: 9, y: 9, solid: false },
    { type: "rootboundHangingRootsForeground", x: 4, y: 8, solid: false },
    { type: "rootboundHangingRootsForeground", x: 11, y: 8, solid: false },
  ],
};
