// Set `source` to a file beneath react-vite/public/art. The same catalog ID can
// then be reused in every room without importing the image again.
export const ART_CATALOG = {
  tiles: {
    grass: { source: "/art/tiles/forest-grass.png" },
    gr: { source: "/art/tiles/forest-grass.png" },
    dirt: { source: "/art/tiles/forest-dirt.png" },
    pt: { source: "/art/tiles/forest-dirt.png" },
    desert: { source: "/art/tiles/desert-sand.png" },
    dt: { source: "/art/tiles/desert-sand.png" },
    ds: { source: "/art/tiles/desert-sand.png" },
    desertAlt: { source: "/art/tiles/desert-cracked-sand.png" },
    sa: { source: "/art/tiles/desert-cracked-sand.png" },
    ck: { source: "/art/tiles/desert-cracked-sand.png" },
    du: { source: "/art/tiles/desert-dune.png" },
    dc: { source: "/art/tiles/desert-cliff.png" },
    ca: {
      source: "/art/props/desert-cactus.png",
      width: 72,
      height: 96,
      offsetX: -4,
      offsetY: -32,
    },
    db: {
      source: "/art/props/desert-dry-bush.png",
      width: 56,
      height: 48,
      offsetX: 4,
      offsetY: 16,
    },
    bn: {
      source: "/art/props/desert-bones.png",
      width: 72,
      height: 48,
      offsetX: -4,
      offsetY: 16,
    },
    dr: {
      source: "/art/props/desert-rock.png",
      width: 80,
      height: 64,
      offsetX: -8,
    },
    ru: {
      source: "/art/props/desert-ruins.png",
      width: 144,
      height: 144,
      offsetX: -40,
      offsetY: -80,
    },
    oa: {
      source: "/art/props/desert-oasis.png",
      width: 160,
      height: 128,
      offsetX: -48,
      offsetY: -64,
    },
    water: { source: "/art/tiles/deep-water.png" },
    dw: { source: "/art/tiles/deep-water.png" },
    sh: { source: "/art/tiles/coast-shore.png" },
    ow: {
      frames: [
        "/art/tiles/open-water-a.png",
        "/art/tiles/open-water-b.png",
      ],
      frameDuration: 360,
    },
    fm: {
      source: "/art/props/coast-foam.png",
      width: 96,
      height: 48,
      offsetX: -16,
      offsetY: 8,
    },
    re: {
      source: "/art/props/coast-reeds.png",
      width: 64,
      height: 80,
      offsetY: -16,
    },
    bridge: { source: "/art/props/bridge-vertical.png" },
    br: { source: "/art/props/bridge-vertical.png" },
    vh: {
      source: "/art/buildings/village-house.png",
      width: 256,
      height: 192,
      offsetX: -96,
      offsetY: -128,
    },
    vs: {
      source: "/art/buildings/village-shop.png",
      width: 256,
      height: 192,
      offsetX: -96,
      offsetY: -128,
    },
    fn: {
      source: "/art/props/village-fence.png",
      width: 96,
      height: 48,
      offsetX: -16,
      offsetY: 16,
    },
    sg: {
      source: "/art/props/village-sign.png",
      width: 56,
      height: 72,
      offsetX: 4,
      offsetY: -8,
    },
    lp: {
      source: "/art/props/village-lamp.png",
      width: 64,
      height: 96,
      offsetY: -32,
    },
    wl: {
      source: "/art/props/village-well.png",
      width: 112,
      height: 112,
      offsetX: -24,
      offsetY: -48,
    },
    cf: { source: "/art/tiles/forest-cliff.png" },
    sw: { source: "/art/tiles/shallow-water.png" },
    le: { source: "/art/tiles/forest-ledge.png" },
    ss: { source: "/art/tiles/stone-stairs.png" },
    rk: { source: "/art/tiles/rock.png" },
    tr: {
      source: "/art/props/forest-tree.png",
      width: 96,
      height: 96,
      offsetX: -16,
      offsetY: -32,
    },
    bu: {
      source: "/art/props/forest-bush.png",
      width: 64,
      height: 48,
      offsetY: 16,
    },
    fl: {
      source: "/art/props/forest-flowers.png",
      width: 48,
      height: 48,
      offsetX: 8,
      offsetY: 12,
    },
    ms: {
      source: "/art/props/forest-mushrooms.png",
      width: 48,
      height: 48,
      offsetX: 8,
      offsetY: 12,
    },
    sp: {
      source: "/art/props/forest-stump.png",
      width: 48,
      height: 48,
      offsetX: 8,
      offsetY: 16,
    },
    lg: {
      source: "/art/props/forest-log.png",
      width: 96,
      height: 48,
      offsetX: -16,
      offsetY: 16,
    },
    tg: { source: "/art/props/forest-tall-grass.png" },
  },
  props: {
    forestTree: {
      source: "/art/props/forest-tree.png",
      width: 96,
      height: 96,
      offsetX: -16,
      offsetY: -32,
    },
    forestBush: {
      source: "/art/props/forest-bush.png",
      width: 64,
      height: 48,
      offsetY: 16,
    },
    forestFlowers: {
      source: "/art/props/forest-flowers.png",
      width: 48,
      height: 48,
      offsetX: 8,
      offsetY: 12,
    },
    forestMushrooms: {
      source: "/art/props/forest-mushrooms.png",
      width: 48,
      height: 48,
      offsetX: 8,
      offsetY: 12,
    },
    forestStump: {
      source: "/art/props/forest-stump.png",
      width: 48,
      height: 48,
      offsetX: 8,
      offsetY: 16,
    },
    forestLog: {
      source: "/art/props/forest-log.png",
      width: 96,
      height: 48,
      offsetX: -16,
      offsetY: 16,
    },
    forestTallGrass: { source: "/art/props/forest-tall-grass.png" },
    bridgeVertical: { source: "/art/props/bridge-vertical.png" },
    villageFence: {
      source: "/art/props/village-fence.png",
      width: 96,
      height: 48,
      offsetX: -16,
      offsetY: 16,
    },
    villageSign: {
      source: "/art/props/village-sign.png",
      width: 56,
      height: 72,
      offsetX: 4,
      offsetY: -8,
    },
    villageLamp: {
      source: "/art/props/village-lamp.png",
      width: 64,
      height: 96,
      offsetY: -32,
    },
    villageWell: {
      source: "/art/props/village-well.png",
      width: 112,
      height: 112,
      offsetX: -24,
      offsetY: -48,
    },
    desertCactus: {
      source: "/art/props/desert-cactus.png",
      width: 72,
      height: 96,
      offsetX: -4,
      offsetY: -32,
    },
    desertDryBush: {
      source: "/art/props/desert-dry-bush.png",
      width: 56,
      height: 48,
      offsetX: 4,
      offsetY: 16,
    },
    desertBones: {
      source: "/art/props/desert-bones.png",
      width: 72,
      height: 48,
      offsetX: -4,
      offsetY: 16,
    },
    desertRock: {
      source: "/art/props/desert-rock.png",
      width: 80,
      height: 64,
      offsetX: -8,
    },
    desertRuins: {
      source: "/art/props/desert-ruins.png",
      width: 144,
      height: 144,
      offsetX: -40,
      offsetY: -80,
    },
    desertOasis: {
      source: "/art/props/desert-oasis.png",
      width: 160,
      height: 128,
      offsetX: -48,
      offsetY: -64,
    },
    coastFoam: {
      source: "/art/props/coast-foam.png",
      width: 96,
      height: 48,
      offsetX: -16,
      offsetY: 8,
    },
    coastReeds: {
      source: "/art/props/coast-reeds.png",
      width: 64,
      height: 80,
      offsetY: -16,
    },
  },
  buildings: {
    villageHouse: {
      source: "/art/buildings/village-house.png",
      width: 256,
      height: 192,
      offsetX: -96,
      offsetY: -128,
    },
    villageShop: {
      source: "/art/buildings/village-shop.png",
      width: 256,
      height: 192,
      offsetX: -96,
      offsetY: -128,
    },
  },
  enemies: {},
  characters: {},
  effects: {},
  ui: {},
};

export function catalogArt(category, id) {
  return ART_CATALOG[category]?.[id];
}
