// Set `source` to a file beneath react-vite/public/art. The same catalog ID can
// then be reused in every room without importing the image again.
export const ART_CATALOG = {
  tiles: {
    grass: { source: "/art/tiles/forest-grass.png" },
    gr: { source: "/art/tiles/forest-grass.png" },
    dirt: { source: "/art/tiles/forest-dirt.png" },
    pt: { source: "/art/tiles/forest-dirt.png" },
    desert: { source: "/art/tiles/desert-sand.png" },
    dt: { source: "/art/tiles/desert-sand.png" },
    ds: { source: "/art/tiles/desert-sand.png" },
    desertAlt: { source: "/art/tiles/desert-cracked-sand.png" },
    sa: { source: "/art/tiles/desert-cracked-sand.png" },
    ck: { source: "/art/tiles/desert-cracked-sand.png" },
    du: { source: "/art/tiles/desert-dune.png" },
    dc: { source: "/art/tiles/desert-cliff.png" },
    ca: {
      source: "/art/props/desert-cactus.png",
      width: 72,
      height: 96,
      offsetX: -4,
      offsetY: -32,
    },
    db: {
      source: "/art/props/desert-dry-bush.png",
      width: 56,
      height: 48,
      offsetX: 4,
      offsetY: 16,
    },
    bn: {
      source: "/art/props/desert-bones.png",
      width: 72,
      height: 48,
      offsetX: -4,
      offsetY: 16,
    },
    dr: {
      source: "/art/props/desert-rock.png",
      width: 80,
      height: 64,
      offsetX: -8,
    },
    ru: {
      source: "/art/props/desert-ruins.png",
      width: 144,
      height: 144,
      offsetX: -40,
      offsetY: -80,
    },
    oa: {
      source: "/art/props/desert-oasis.png",
      width: 160,
      height: 128,
      offsetX: -48,
      offsetY: -64,
    },
    water: { source: "/art/tiles/deep-water.png" },
    dw: { source: "/art/tiles/deep-water.png" },
    sh: { source: "/art/tiles/coast-shore.png" },
    ow: {
      frames: [
        "/art/tiles/open-water-a.png",
        "/art/tiles/open-water-b.png",
      ],
      frameDuration: 360,
    },
    fm: {
      source: "/art/props/coast-foam.png",
      width: 96,
      height: 48,
      offsetX: -16,
      offsetY: 8,
    },
    re: {
      source: "/art/props/coast-reeds.png",
      width: 64,
      height: 80,
      offsetY: -16,
    },
    dk: {
      source: "/art/props/coast-dock.png",
      width: 64,
      height: 128,
      offsetY: -64,
    },
    bt: {
      source: "/art/props/coast-boat.png",
      width: 96,
      height: 128,
      offsetX: -16,
      offsetY: -64,
    },
    wf: {
      source: "/art/props/coast-waterfall.png",
      width: 64,
      height: 128,
      offsetY: -64,
    },
    ly: {
      source: "/art/props/coast-lily-pad.png",
      width: 64,
      height: 56,
      offsetY: 8,
    },
    co: {
      source: "/art/props/coast-coral.png",
      width: 72,
      height: 72,
      offsetX: -4,
      offsetY: -8,
    },
    cv: { source: "/art/tiles/cave-floor.png" },
    cw: { source: "/art/tiles/cave-wall.png" },
    cp: { source: "/art/tiles/cave-pit.png" },
    cm: {
      source: "/art/props/cave-stalagmite.png",
      width: 80,
      height: 104,
      offsetX: -8,
      offsetY: -40,
    },
    cb: {
      source: "/art/props/cave-bones.png",
      width: 72,
      height: 56,
      offsetX: -4,
      offsetY: 8,
    },
    ct: {
      source: "/art/props/cave-torch.png",
      width: 48,
      height: 72,
      offsetX: 8,
      offsetY: -8,
    },
    xf: { source: "/art/tiles/crystal-floor.png" },
    xw: { source: "/art/tiles/crystal-wall.png" },
    xs: {
      source: "/art/props/crystal-small.png",
      width: 64,
      height: 64,
    },
    xl: {
      source: "/art/props/crystal-large.png",
      width: 144,
      height: 128,
      offsetX: -40,
      offsetY: -64,
    },
    mf: { source: "/art/tiles/dungeon-mainframe-floor.png" },
    mw: { source: "/art/tiles/dungeon-mainframe-wall.png" },
    rf: { source: "/art/tiles/dungeon-reactor-floor.png" },
    rw: { source: "/art/tiles/dungeon-reactor-wall.png" },
    sf: { source: "/art/tiles/dungeon-server-floor.png" },
    sv: { source: "/art/tiles/dungeon-server-wall.png" },
    dd: {
      source: "/art/props/dungeon-door.png",
      width: 96,
      height: 128,
      offsetX: -16,
      offsetY: -64,
    },
    dl: {
      source: "/art/props/dungeon-locked-door.png",
      width: 96,
      height: 128,
      offsetX: -16,
      offsetY: -64,
    },
    eb: {
      source: "/art/props/dungeon-barrier.png",
      width: 160,
      height: 80,
      offsetX: -48,
      offsetY: -16,
    },
    ps: { source: "/art/props/dungeon-switch.png" },
    gs: {
      source: "/art/props/dungeon-statue.png",
      width: 112,
      height: 144,
      offsetX: -24,
      offsetY: -80,
    },
    pi: {
      source: "/art/props/dungeon-pillar.png",
      width: 96,
      height: 144,
      offsetX: -16,
      offsetY: -80,
    },
    ch: {
      source: "/art/props/dungeon-chest.png",
      width: 80,
      height: 64,
      offsetX: -8,
    },
    po: {
      source: "/art/props/dungeon-pot.png",
      width: 64,
      height: 72,
      offsetY: -8,
    },
    qc: {
      source: "/art/props/dungeon-crate.png",
      width: 72,
      height: 72,
      offsetX: -4,
      offsetY: -8,
    },
    tm: {
      source: "/art/props/dungeon-terminal.png",
      width: 80,
      height: 104,
      offsetX: -8,
      offsetY: -40,
    },
    tp: { source: "/art/props/dungeon-spike-trap.png" },
    dn: {
      source: "/art/props/dungeon-stairs.png",
      width: 96,
      height: 80,
      offsetX: -16,
      offsetY: -16,
    },
    pg: {
      source: "/art/props/dungeon-portal.png",
      width: 112,
      height: 112,
      offsetX: -24,
      offsetY: -48,
    },
    bridge: { source: "/art/props/bridge-vertical.png" },
    br: { source: "/art/props/bridge-vertical.png" },
    vh: {
      source: "/art/buildings/village-house.png",
      width: 256,
      height: 192,
      offsetX: -96,
      offsetY: -128,
    },
    vs: {
      source: "/art/buildings/village-shop.png",
      width: 256,
      height: 192,
      offsetX: -96,
      offsetY: -128,
    },
    fn: {
      source: "/art/props/village-fence.png",
      width: 96,
      height: 48,
      offsetX: -16,
      offsetY: 16,
    },
    sg: {
      source: "/art/props/village-sign.png",
      width: 56,
      height: 72,
      offsetX: 4,
      offsetY: -8,
    },
    lp: {
      source: "/art/props/village-lamp.png",
      width: 64,
      height: 96,
      offsetY: -32,
    },
    wl: {
      source: "/art/props/village-well.png",
      width: 112,
      height: 112,
      offsetX: -24,
      offsetY: -48,
    },
    cf: { source: "/art/tiles/forest-cliff.png" },
    sw: { source: "/art/tiles/shallow-water.png" },
    le: { source: "/art/tiles/forest-ledge.png" },
    ss: { source: "/art/tiles/stone-stairs.png" },
    rk: { source: "/art/tiles/rock.png" },
    tr: {
      source: "/art/props/forest-tree.png",
      width: 96,
      height: 96,
      offsetX: -16,
      offsetY: -32,
    },
    bu: {
      source: "/art/props/forest-bush.png",
      width: 64,
      height: 48,
      offsetY: 16,
    },
    fl: {
      source: "/art/props/forest-flowers.png",
      width: 48,
      height: 48,
      offsetX: 8,
      offsetY: 12,
    },
    ms: {
      source: "/art/props/forest-mushrooms.png",
      width: 48,
      height: 48,
      offsetX: 8,
      offsetY: 12,
    },
    sp: {
      source: "/art/props/forest-stump.png",
      width: 48,
      height: 48,
      offsetX: 8,
      offsetY: 16,
    },
    lg: {
      source: "/art/props/forest-log.png",
      width: 96,
      height: 48,
      offsetX: -16,
      offsetY: 16,
    },
    tg: { source: "/art/props/forest-tall-grass.png" },
  },
  props: {
    forestTree: {
      source: "/art/props/forest-tree.png",
      width: 96,
      height: 96,
      offsetX: -16,
      offsetY: -32,
    },
    forestBush: {
      source: "/art/props/forest-bush.png",
      width: 64,
      height: 48,
      offsetY: 16,
    },
    forestFlowers: {
      source: "/art/props/forest-flowers.png",
      width: 48,
      height: 48,
      offsetX: 8,
      offsetY: 12,
    },
    forestMushrooms: {
      source: "/art/props/forest-mushrooms.png",
      width: 48,
      height: 48,
      offsetX: 8,
      offsetY: 12,
    },
    forestStump: {
      source: "/art/props/forest-stump.png",
      width: 48,
      height: 48,
      offsetX: 8,
      offsetY: 16,
    },
    forestLog: {
      source: "/art/props/forest-log.png",
      width: 96,
      height: 48,
      offsetX: -16,
      offsetY: 16,
    },
    forestTallGrass: { source: "/art/props/forest-tall-grass.png" },
    bridgeVertical: { source: "/art/props/bridge-vertical.png" },
    villageFence: {
      source: "/art/props/village-fence.png",
      width: 96,
      height: 48,
      offsetX: -16,
      offsetY: 16,
    },
    villageSign: {
      source: "/art/props/village-sign.png",
      width: 56,
      height: 72,
      offsetX: 4,
      offsetY: -8,
    },
    villageLamp: {
      source: "/art/props/village-lamp.png",
      width: 64,
      height: 96,
      offsetY: -32,
    },
    villageWell: {
      source: "/art/props/village-well.png",
      width: 112,
      height: 112,
      offsetX: -24,
      offsetY: -48,
    },
    desertCactus: {
      source: "/art/props/desert-cactus.png",
      width: 72,
      height: 96,
      offsetX: -4,
      offsetY: -32,
    },
    desertDryBush: {
      source: "/art/props/desert-dry-bush.png",
      width: 56,
      height: 48,
      offsetX: 4,
      offsetY: 16,
    },
    desertBones: {
      source: "/art/props/desert-bones.png",
      width: 72,
      height: 48,
      offsetX: -4,
      offsetY: 16,
    },
    desertRock: {
      source: "/art/props/desert-rock.png",
      width: 80,
      height: 64,
      offsetX: -8,
    },
    desertRuins: {
      source: "/art/props/desert-ruins.png",
      width: 144,
      height: 144,
      offsetX: -40,
      offsetY: -80,
    },
    desertOasis: {
      source: "/art/props/desert-oasis.png",
      width: 160,
      height: 128,
      offsetX: -48,
      offsetY: -64,
    },
    coastFoam: {
      source: "/art/props/coast-foam.png",
      width: 96,
      height: 48,
      offsetX: -16,
      offsetY: 8,
    },
    coastReeds: {
      source: "/art/props/coast-reeds.png",
      width: 64,
      height: 80,
      offsetY: -16,
    },
    coastDock: {
      source: "/art/props/coast-dock.png",
      width: 64,
      height: 128,
      offsetY: -64,
    },
    coastBoat: {
      source: "/art/props/coast-boat.png",
      width: 96,
      height: 128,
      offsetX: -16,
      offsetY: -64,
    },
    coastWaterfall: {
      source: "/art/props/coast-waterfall.png",
      width: 64,
      height: 128,
      offsetY: -64,
    },
    coastLilyPad: {
      source: "/art/props/coast-lily-pad.png",
      width: 64,
      height: 56,
      offsetY: 8,
    },
    coastCoral: {
      source: "/art/props/coast-coral.png",
      width: 72,
      height: 72,
      offsetX: -4,
      offsetY: -8,
    },
    caveStalagmite: {
      source: "/art/props/cave-stalagmite.png",
      width: 80,
      height: 104,
      offsetX: -8,
      offsetY: -40,
    },
    caveBones: {
      source: "/art/props/cave-bones.png",
      width: 72,
      height: 56,
      offsetX: -4,
      offsetY: 8,
    },
    caveTorch: {
      source: "/art/props/cave-torch.png",
      width: 48,
      height: 72,
      offsetX: 8,
      offsetY: -8,
    },
    crystalSmall: {
      source: "/art/props/crystal-small.png",
      width: 64,
      height: 64,
    },
    crystalLarge: {
      source: "/art/props/crystal-large.png",
      width: 144,
      height: 128,
      offsetX: -40,
      offsetY: -64,
    },
    dungeonDoor: {
      source: "/art/props/dungeon-door.png",
      width: 96,
      height: 128,
      offsetX: -16,
      offsetY: -64,
    },
    dungeonLockedDoor: {
      source: "/art/props/dungeon-locked-door.png",
      width: 96,
      height: 128,
      offsetX: -16,
      offsetY: -64,
    },
    dungeonBarrier: {
      source: "/art/props/dungeon-barrier.png",
      width: 160,
      height: 80,
      offsetX: -48,
      offsetY: -16,
    },
    dungeonSwitch: { source: "/art/props/dungeon-switch.png" },
    dungeonStatue: {
      source: "/art/props/dungeon-statue.png",
      width: 112,
      height: 144,
      offsetX: -24,
      offsetY: -80,
    },
    dungeonPillar: {
      source: "/art/props/dungeon-pillar.png",
      width: 96,
      height: 144,
      offsetX: -16,
      offsetY: -80,
    },
    dungeonChest: {
      source: "/art/props/dungeon-chest.png",
      width: 80,
      height: 64,
      offsetX: -8,
    },
    dungeonPot: {
      source: "/art/props/dungeon-pot.png",
      width: 64,
      height: 72,
      offsetY: -8,
    },
    dungeonCrate: {
      source: "/art/props/dungeon-crate.png",
      width: 72,
      height: 72,
      offsetX: -4,
      offsetY: -8,
    },
    dungeonTerminal: {
      source: "/art/props/dungeon-terminal.png",
      width: 80,
      height: 104,
      offsetX: -8,
      offsetY: -40,
    },
    dungeonSpikeTrap: { source: "/art/props/dungeon-spike-trap.png" },
    dungeonStairs: {
      source: "/art/props/dungeon-stairs.png",
      width: 96,
      height: 80,
      offsetX: -16,
      offsetY: -16,
    },
    dungeonPortal: {
      source: "/art/props/dungeon-portal.png",
      width: 112,
      height: 112,
      offsetX: -24,
      offsetY: -48,
    },
  },
  buildings: {
    villageHouse: {
      source: "/art/buildings/village-house.png",
      width: 256,
      height: 192,
      offsetX: -96,
      offsetY: -128,
    },
    villageShop: {
      source: "/art/buildings/village-shop.png",
      width: 256,
      height: 192,
      offsetX: -96,
      offsetY: -128,
    },
  },
  enemies: {
    forestByteBeetle: {
      source: "/art/enemies/forest-byte-beetle.png",
      width: 72,
      height: 64,
      offsetX: -4,
    },
    caveEchoBat: {
      source: "/art/enemies/cave-echo-bat.png",
      width: 80,
      height: 64,
      offsetX: -8,
    },
    desertSandSkitter: {
      source: "/art/enemies/desert-sand-skitter.png",
      width: 80,
      height: 72,
      offsetX: -8,
      offsetY: -8,
    },
    waterCurrentBlob: {
      source: "/art/enemies/water-current-blob.png",
      width: 72,
      height: 72,
      offsetX: -4,
      offsetY: -8,
    },
    dungeonFirewallDrone: {
      source: "/art/enemies/dungeon-firewall-drone.png",
      width: 72,
      height: 72,
      offsetX: -4,
      offsetY: -8,
    },
    // Existing room enemy names use the new catalog art automatically.
    slime: {
      source: "/art/enemies/water-current-blob.png",
      width: 72,
      height: 72,
      offsetX: -4,
      offsetY: -8,
    },
    bat: {
      source: "/art/enemies/cave-echo-bat.png",
      width: 80,
      height: 64,
      offsetX: -8,
    },
    guard: {
      source: "/art/enemies/dungeon-firewall-drone.png",
      width: 72,
      height: 72,
      offsetX: -4,
      offsetY: -8,
    },
    minibossNullKnight: {
      source: "/art/enemies/miniboss-null-knight.png",
      width: 96,
      height: 96,
      offsetX: -16,
      offsetY: -24,
    },
    bossCacheColossus: {
      source: "/art/enemies/boss-cache-colossus.png",
      width: 128,
      height: 128,
      offsetX: -32,
      offsetY: -48,
    },
    bossFluxSovereign: {
      source: "/art/enemies/boss-flux-sovereign.png",
      width: 128,
      height: 128,
      offsetX: -32,
      offsetY: -48,
    },
    bossRootWarden: {
      source: "/art/enemies/boss-root-warden.png",
      width: 128,
      height: 128,
      offsetX: -32,
      offsetY: -48,
    },
    // Legacy boss names remain valid for older custom rooms.
    knight: {
      source: "/art/enemies/miniboss-null-knight.png",
      width: 96,
      height: 96,
      offsetX: -16,
      offsetY: -24,
    },
    boss: {
      source: "/art/enemies/boss-cache-colossus.png",
      width: 128,
      height: 128,
      offsetX: -32,
      offsetY: -48,
    },
    mage: {
      source: "/art/enemies/boss-flux-sovereign.png",
      width: 128,
      height: 128,
      offsetX: -32,
      offsetY: -48,
    },
  },
  characters: {
    playerWalk: {
      source: "/art/characters/player-walk-sheet.png",
      sheet: {
        columns: 4,
        rows: 4,
        frameWidth: 314,
        frameHeight: 314,
        framesPerDirection: 4,
        directions: ["down", "left", "right", "up"],
      },
      frameDuration: 130,
      loop: true,
    },
    playerAttack: {
      source: "/art/characters/player-attack-sheet.png",
      sheet: {
        columns: 4,
        rows: 4,
        frameWidth: 314,
        frameHeight: 314,
        framesPerDirection: 4,
        directions: ["down", "left", "right", "up"],
      },
      frameDuration: 85,
      loop: false,
    },
    playerItemUse: {
      source: "/art/characters/player-item-use-sheet.png",
      sheet: {
        columns: 4,
        rows: 4,
        frameWidth: 314,
        frameHeight: 314,
        framesPerDirection: 4,
        directions: ["down", "left", "right", "up"],
      },
      frameDuration: 120,
      loop: false,
    },
    playerHurt: {
      source: "/art/characters/player-hurt-sheet.png",
      sheet: {
        columns: 4,
        rows: 4,
        frameWidth: 314,
        frameHeight: 314,
        framesPerDirection: 4,
        directions: ["down", "left", "right", "up"],
      },
      frameDuration: 110,
      loop: false,
    },
    playerFall: {
      source: "/art/characters/player-fall-sheet.png",
      sheet: {
        columns: 4,
        rows: 4,
        frameWidth: 314,
        frameHeight: 314,
        framesPerDirection: 4,
        directions: ["down", "left", "right", "up"],
      },
      frameDuration: 120,
      loop: false,
    },
    villagerGardener: {
      source: "/art/characters/villager-gardener.png",
      width: 72,
      height: 96,
      offsetX: -4,
      offsetY: -32,
    },
    villagerMechanic: {
      source: "/art/characters/villager-mechanic.png",
      width: 72,
      height: 96,
      offsetX: -4,
      offsetY: -32,
    },
    merchantTraveler: {
      source: "/art/characters/merchant-traveler.png",
      width: 88,
      height: 112,
      offsetX: -12,
      offsetY: -48,
    },
    merchantTechnician: {
      source: "/art/characters/merchant-technician.png",
      width: 88,
      height: 112,
      offsetX: -12,
      offsetY: -48,
    },
    questArchivist: {
      source: "/art/characters/quest-archivist.png",
      width: 80,
      height: 112,
      offsetX: -8,
      offsetY: -48,
    },
    questNetworkScout: {
      source: "/art/characters/quest-network-scout.png",
      width: 80,
      height: 104,
      offsetX: -8,
      offsetY: -40,
    },
  },
  items: {
    htmlSword: { source: "/art/items/html-sword.png" },
    boomerang: { source: "/art/items/callback-drone.png" },
    bow: { source: "/art/items/css-pulsecaster.png" },
    bombs: { source: "/art/items/code-bomb.png" },
    hookshot: { source: "/art/items/api-grappler.png" },
    fireRod: { source: "/art/items/firewall-breaker.png" },
    iceRod: { source: "/art/items/freeze-debugger.png" },
    hammer: { source: "/art/items/refactor-hammer.png" },
    lantern: { source: "/art/items/dark-mode-lamp.png" },
    mirror: { source: "/art/items/git-revert-mirror.png" },
    cape: { source: "/art/items/vpn-cloak.png" },
    medallion: { source: "/art/items/root-access-medallion.png" },
    devJacket: { source: "/art/items/dev-jacket.png" },
    shield: { source: "/art/items/debug-shield.png" },
    glove: { source: "/art/items/power-gloves.png" },
    boots: { source: "/art/items/speed-boots.png" },
  },
  effects: {
    cssPulse: { source: "/art/effects/css-pulse.png" },
    codeExplosion: { source: "/art/effects/code-explosion.png" },
    htmlSlash: { source: "/art/effects/html-slash.png" },
    firewallBurst: { source: "/art/effects/firewall-burst.png" },
    freezeBurst: { source: "/art/effects/freeze-burst.png" },
    rootSurge: { source: "/art/effects/root-surge.png" },
  },
  ui: {
    heartFull: { source: "/art/ui/heart-full.png" },
    heartEmpty: { source: "/art/ui/heart-empty.png" },
    magicMeterFrame: { source: "/art/ui/magic-meter-frame.png" },
    creditToken: { source: "/art/ui/credit-token.png" },
    accessKey: { source: "/art/ui/access-key.png" },
    itemSlotFrame: { source: "/art/ui/item-slot-frame.png" },
    dialogueFrame: { source: "/art/ui/dialogue-frame.png" },
    menuPanelFrame: { source: "/art/ui/menu-panel-frame.png" },
    mapRoomFrame: { source: "/art/ui/map-room-frame.png" },
    mapMarkerPlayer: { source: "/art/ui/map-marker-player.png" },
    mapMarkerCache: { source: "/art/ui/map-marker-cache.png" },
    mapMarkerShop: { source: "/art/ui/map-marker-shop.png" },
    selectionCursor: { source: "/art/ui/selection-cursor.png" },
  },
};

export function catalogArt(category, id) {
  return ART_CATALOG[category]?.[id];
}
