export const ART_V2_CATALOG = {
  tiles: {
    grass: { source: "/art/v2/tiles/grass-a.svg" },
    grassAlt: { source: "/art/v2/tiles/grass-b.svg" },
    village: { source: "/art/v2/tiles/village-path.svg" },
    dirt: { source: "/art/v2/tiles/village-path.svg" },
    pt: { source: "/art/v2/tiles/village-path.svg" },
    forest: { source: "/art/v2/tiles/forest-cliff.svg" },
    forestWall: { source: "/art/v2/tiles/forest-cliff.svg" },
    mountain: { source: "/art/v2/tiles/forest-cliff.svg" },
    cf: { source: "/art/v2/tiles/forest-cliff.svg" },
    stone: { source: "/art/v2/tiles/stone-floor.svg" },
    stoneAlt: { source: "/art/v2/tiles/stone-floor.svg" },
    dungeonFloor: { source: "/art/v2/tiles/cave-floor.svg" },
    dungeonFloorAlt: { source: "/art/v2/tiles/cave-floor-alt.svg" },
    cv: { source: "/art/v2/tiles/cave-floor.svg" },
    wall: { source: "/art/v2/tiles/cave-wall.svg" },
    cw: { source: "/art/v2/tiles/cave-wall.svg" },
    crackedWall: { source: "/art/v2/tiles/cave-wall.svg" },
    ledgeDown: { source: "/art/v2/tiles/ledge-down.svg" },
    le: { source: "/art/v2/tiles/ledge-down.svg" },
    stairs: { source: "/art/v2/tiles/stone-stairs.svg" },
    ss: { source: "/art/v2/tiles/stone-stairs.svg" },
    pit: { source: "/art/v2/tiles/pit.svg" },
    cp: { source: "/art/v2/tiles/pit.svg" },
    water: {
      frames: ["/art/v2/tiles/water-a.svg", "/art/v2/tiles/water-b.svg"],
      frameDuration: 420,
    },
    ow: {
      frames: ["/art/v2/tiles/water-a.svg", "/art/v2/tiles/water-b.svg"],
      frameDuration: 420,
    },
    deepWater: { source: "/art/v2/tiles/deep-water.svg" },
    dw: { source: "/art/v2/tiles/deep-water.svg" },
    sw: { source: "/art/v2/tiles/shallow-water.svg" },
    desert: { source: "/art/v2/tiles/desert-sand.svg" },
    dt: { source: "/art/v2/tiles/desert-sand.svg" },
    ds: { source: "/art/v2/tiles/desert-sand.svg" },
    desertAlt: { source: "/art/v2/tiles/desert-cracked.svg" },
    sa: { source: "/art/v2/tiles/desert-cracked.svg" },
    ck: { source: "/art/v2/tiles/desert-cracked.svg" },
    rf: { source: "/art/v2/tiles/desert-cracked.svg" },
    dc: { source: "/art/v2/tiles/desert-cliff.svg" },
    rw: { source: "/art/v2/tiles/desert-cliff.svg" },
  },
  props: {
    forestTree: {
      source: "/art/v2/props/forest-tree.svg",
      width: 96,
      height: 112,
      offsetX: -16,
      offsetY: -48,
    },
    forestBush: {
      source: "/art/v2/props/forest-bush.svg",
      width: 72,
      height: 56,
      offsetX: -4,
      offsetY: 8,
    },
    forestTallGrass: { source: "/art/v2/props/tall-grass.svg" },
    forestFlowers: {
      source: "/art/v2/props/forest-flowers.svg",
      width: 48,
      height: 48,
      offsetX: 8,
      offsetY: 12,
    },
    forestMushrooms: {
      source: "/art/v2/props/forest-mushrooms.svg",
      width: 48,
      height: 48,
      offsetX: 8,
      offsetY: 12,
    },
    villageWell: {
      source: "/art/v2/props/village-well.svg",
      width: 112,
      height: 112,
      offsetX: -24,
      offsetY: -48,
    },
    villageSign: {
      source: "/art/v2/props/village-sign.svg",
      width: 56,
      height: 72,
      offsetX: 4,
      offsetY: -8,
    },
    villageLamp: {
      source: "/art/v2/props/village-lamp.svg",
      width: 64,
      height: 96,
      offsetY: -32,
    },
    caveStalagmite: {
      source: "/art/v2/props/cave-stalagmite.svg",
      width: 80,
      height: 104,
      offsetX: -8,
      offsetY: -40,
    },
    caveTorch: {
      source: "/art/v2/props/cave-torch.svg",
      width: 48,
      height: 72,
      offsetX: 8,
      offsetY: -8,
    },
    dungeonChest: {
      source: "/art/v2/props/dungeon-chest.svg",
      width: 80,
      height: 64,
      offsetX: -8,
    },
    dungeonPot: {
      source: "/art/v2/props/dungeon-pot.svg",
      width: 64,
      height: 72,
      offsetY: -8,
    },
    dungeonCrate: {
      source: "/art/v2/props/dungeon-crate.svg",
      width: 72,
      height: 72,
      offsetX: -4,
      offsetY: -8,
    },
  },
  buildings: {
    villageHouse: {
      source: "/art/v2/buildings/village-house.svg",
      width: 256,
      height: 192,
      offsetX: -96,
      offsetY: -128,
    },
    villageShop: {
      source: "/art/v2/buildings/village-shop.svg",
      width: 256,
      height: 192,
      offsetX: -96,
      offsetY: -128,
    },
  },
  characters: {
    playerWalk: {
      source: "/art/v2/characters/player-walk-sheet.svg",
      sheet: {
        columns: 4,
        rows: 4,
        frameWidth: 64,
        frameHeight: 64,
        framesPerDirection: 4,
        directions: ["down", "left", "right", "up"],
      },
      frameDuration: 105,
      loop: true,
    },
    villagerGardener: {
      source: "/art/v2/characters/villager-gardener.svg",
      width: 72,
      height: 96,
      offsetX: -4,
      offsetY: -32,
    },
    villagerMechanic: {
      source: "/art/v2/characters/villager-mechanic.svg",
      width: 72,
      height: 96,
      offsetX: -4,
      offsetY: -32,
    },
  },
  enemies: {
    forestByteBeetle: {
      source: "/art/v2/enemies/forest-byte-beetle.svg",
      width: 72,
      height: 64,
      offsetX: -4,
    },
    caveEchoBat: {
      source: "/art/v2/enemies/cave-echo-bat.svg",
      width: 80,
      height: 64,
      offsetX: -8,
    },
    waterCurrentBlob: {
      source: "/art/v2/enemies/water-current-blob.svg",
      width: 72,
      height: 72,
      offsetX: -4,
      offsetY: -8,
    },
    dungeonFirewallDrone: {
      source: "/art/v2/enemies/dungeon-firewall-drone.svg",
      width: 72,
      height: 72,
      offsetX: -4,
      offsetY: -8,
    },
    desertSandSkitter: {
      source: "/art/v2/enemies/desert-sand-skitter.svg",
      width: 80,
      height: 72,
      offsetX: -8,
      offsetY: -8,
    },
    slime: {
      source: "/art/v2/enemies/water-current-blob.svg",
      width: 72,
      height: 72,
      offsetX: -4,
      offsetY: -8,
    },
    bat: {
      source: "/art/v2/enemies/cave-echo-bat.svg",
      width: 80,
      height: 64,
      offsetX: -8,
    },
    guard: {
      source: "/art/v2/enemies/dungeon-firewall-drone.svg",
      width: 72,
      height: 72,
      offsetX: -4,
      offsetY: -8,
    },
  },
};

export function catalogArtV2(category, id) {
  return ART_V2_CATALOG[category]?.[id] || null;
}
