export default {
  id: "d02:1,2", name: "Ashen Vestibule", variant: 0,
  wallRects: [[2, 2, 3, 5], [11, 2, 3, 5]],
  floor: [
    ".. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..",
    ".. rf rf rf rf rf rf rf rf rf rf rf rf rf rf ..",
    ".. rf rw rw rw rf rf rf rf rf rf rw rw rw rf ..",
    ".. rf rw rw rw rf rf rf rf rf rf rw rw rw rf ..",
    ".. rf rw rw rw rf rf rf rf rf rf rw rw rw rf ..",
    ".. rf rw rw rw rf rf rf rf rf rf rw rw rw rf ..",
    ".. rf rw rw rw rf rf rf rf rf rf rw rw rw rf ..",
    ".. rf rf rf rf rf rf rf rf rf rf rf rf rf rf ..",
    ".. rf rf rf rf rf rf rf rf rf rf rf rf rf rf ..",
    ".. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..",
  ],
  assets: [
    { type: "dungeonTerminal", x: 8, y: 4, solid: false },
    { type: "caveTorch", x: 6, y: 6, solid: false },
    { type: "caveTorch", x: 9, y: 6, solid: false },
    { type: "dungeonPillar", x: 5, y: 7 },
    { type: "dungeonDoor", x: 7, y: 1, solid: false },
    { type: "reactorConduit", x: 5, y: 3, solid: false },
    { type: "reactorConduit", x: 9, y: 3, solid: false },
    { type: "reactorHeatVent", x: 6, y: 5, solid: false },
    { type: "reactorHeatVent", x: 9, y: 5, solid: false },
    { type: "reactorLavaGrate", x: 7, y: 7, solid: false },
    { type: "reactorGantryForeground", x: 7, y: 9, solid: false },
  ],
};
