export default {
  id: "d02:1,1", name: "Pressure Core", variant: 0,
  wallRects: [[2, 2, 3, 1], [11, 2, 3, 1], [2, 7, 4, 1], [10, 7, 4, 1]],
  floor: [
    ".. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..",
    ".. rf rf rf rf rf rf rf rf rf rf rf rf rf rf ..",
    ".. rf rw rw rw rf rf rf rf rf rf rw rw rw rf ..",
    ".. rf rf rf rf rf rf rf rf rf rf rf rf rf rf ..",
    ".. rf rf rf rf rm rm rf rf rf rm rm rf rf rf ..",
    ".. rf rf rf rf rm rm rf rf rf rm rm rf rf rf ..",
    ".. rf rf rf rf rf rf rf rf rf rf rf rf rf rf ..",
    ".. rf rw rw rw rw rf rf rf rf rw rw rw rw rf ..",
    ".. rf rf rf rf rf rf rf rf rf rf rf rf rf rf ..",
    ".. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..",
  ],
  assets: [
    { type: "dungeonPillar", x: 3, y: 4 },
    { type: "dungeonPillar", x: 12, y: 4 },
    { type: "dungeonTerminal", x: 8, y: 5, solid: false },
    { type: "dungeonBarrier", x: 7, y: 6, solid: false },
    { type: "caveTorch", x: 6, y: 3, solid: false },
    { type: "caveTorch", x: 9, y: 3, solid: false },
    { type: "reactorCore", x: 7, y: 4, solid: false },
    { type: "reactorHeatVent", x: 5, y: 5, solid: false },
    { type: "reactorHeatVent", x: 10, y: 5, solid: false },
    { type: "reactorLavaGrate", x: 6, y: 7, solid: false },
    { type: "reactorLavaGrate", x: 9, y: 7, solid: false },
    { type: "reactorGantryForeground", x: 7, y: 9, solid: false },
  ],
};
